### ISSUE TITLE
broken link at description and/or missing moved-to repo

### ISSUE THREAD

**Issue by birbilis** [xuzhg/OData.OpenAPI#5]
at description it says "and https://github.com/microsoft/openapi.net.odata for basic CSDL to Open API DOM." but that link is broken

btw, it seems microsoftgraph/microsoft-graph-openapi repo's readme.md is pointing to that same broken URL too (see issue https://github.com/microsoftgraph/microsoft-graph-openapi/issues/4)

do you know what the correct URL is or maybe can you see to that repo being instantiated, in case it never reached its destination on github?

**Comment by xuzhg** [comment]
@birbilis "https://github.com/microsoft/openapi.net.odata" is not broken. It's still in **Private** status so that you maybe not access it. We are working to public it soon. Thanks.

**Comment by birbilis** [comment]
thanks for clarifying this

**Comment by xuzhg** [comment]
@birbilis the https://github.com/microsoft/openapi.net.odata is published. I think you can access it now. Please let me know any problem and Please share us your feedbacks. Thanks.
